### ISSUE TITLE
zmypy ignores Mypy's "files" setting

### ISSUE THREAD

**Issue by Feuermurmel** [zubanls/zuban#4]
# zmypy ignores Mypy's "files" setting

It seems that `zmypy` ignores Mypy's `files` setting. This is my test project setup:

```
(venv) $ tree --gitignore
.
├── Makefile
├── pyproject.toml
├── readme.md
└── src
    └── hello_zuban
        └── __init__.py
```

Mypy's `mypy_path` is set up to accomodate this:

```toml
# pyproject.toml
[project]
name = "hello_zuban"
version = "0.1.0"

requires-python = ">= 3.12"
dependencies = []

[project.scripts]
hello-zuban = "hello_zuban:entry_point"

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
files = ["$MYPY_CONFIG_FILE_DIR/src"]
strict = true
```

```python
# src/hello_zuban/__init__.py
print("hello")
```

This works with `mypy`, but `zmypy` seems to somehow not decend into the `src` directory and find the source files there: 

```
(venv) michi ~/.../Zuban/hello-zuban$ zmypy
Success: no issues found in 0 source files
(venv) michi ~/.../Zuban/hello-zuban$ mypy
Success: no issues found in 1 source file
```

Python 3.13 \
zmypy 0.0.15 \
macOS 14.7.6
